### PR TITLE
Rebuild for r-base 4.4 and UCRT mingw toolchain

### PR DESCRIPTION
**Pull request by danielnachun**

### CODE REVIEW

**Comment by PertuyF** [comment]
Hi @danielnachun ,
It has been a long time I am not involved in maintaining R packages on Conda Forge. I would not be relevant anymore on such PR for a major migration.
Please see with @conda-forge/r for a proper review.

**Comment by danielnachun** [comment]
Do you want to be removed as a maintainer for this package?  At the moment all pull requests will automatically ask for your review.

**Comment by PertuyF** [comment]
Sure, if there is someone to take over I will gladly leave the spot to active maintainers 🙂

**Comment by danielnachun** [comment]
All R packages are maintained the team of maintainers in @conda-forge/r so there will still be maintainers.  I'll remove your name from maintainers list in this PR so you don't get notified any more.

**Review by bgruening — APPROVED** [review]

**Pull request merged**
